{% set version = "0.3.7" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-profvis
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/profvis_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/profvis/profvis_{{ version }}.tar.gz
  sha256: 43974863cb793f81dbea4b94096343c321f7739c9038980405c9b16b04a906b9

build:
  merge_build_host: true  # [win]
  number: 1
  # Only building r packages for win64, linux64, osx64
  skip: True # [aarch64 or s390x or ppc64le or arm64]

  rpaths:
    - lib/R/lib/
    - lib/

  # weird error on windows
  missing_dso_whitelist:
    - $RPATH/R.dll  # [win]


requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-htmlwidgets              # [build_platform != target_platform]
    - r-stringr                  # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{native}}toolchain          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base {{ r_version }}
    - r-htmlwidgets >=0.3.2
    - r-stringr
  run:
    - r-base {{ r_version }}
    - {{ native }}gcc-libs         # [win]
    - r-htmlwidgets >=0.3.2
    - r-stringr

test:
  commands:
    - $R -e "library('profvis')"           # [not win]
    - "\"%R%\" -e \"library('profvis')\""  # [win]

about:
  home: https://rstudio.github.io/profvis/
  license: GPL-3.0-only
  summary: Interactive visualizations for profiling R code.
  license_family: GPL3

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
    - LICENSE
extra:
  recipe-maintainers:
    - conda-forge/r
    - halldc

  skip-lints:
    # These are needed because of bug: https://github.com/anaconda-distribution/anaconda-linter/issues/197
    - http_url
    - invalid_url

    - host_section_needs_exact_pinnings
    - missing_dev_url
    - missing_description
    - missing_documentation

  anaconda-services:
    ref:  https://anaconda.zendesk.com/agent/tickets/35116
    reason: "needed for r-devtools"
    recipe-maintainers:
      - bkreider


# Package: profvis
# Title: Interactive Visualizations for Profiling R Code
# Version: 0.3.6
# Authors@R: c( person("Winston", "Chang", email = "winston@rstudio.com", role = c("aut", "cre")), person("Javier", "Luraschi", email = "javier@rstudio.com", role = "aut"), person("Timothy", "Mastny", role = "aut"), person(family = "RStudio", role = "cph"), person(family = "jQuery Foundation", role = "cph", comment = "jQuery library"), person(family = "jQuery contributors", role = c("ctb", "cph"), comment = "jQuery library; authors listed in inst/www/shared/jquery-AUTHORS.txt"), person("Mike", "Bostock", role = c("ctb", "cph"), comment = "D3 library"), person(family = "D3 contributors", role = "ctb", comment = "D3 library"), person("Ivan", "Sagalaev", role = c("ctb", "cph"), comment = "highlight.js library") )
# Description: Interactive visualizations for profiling R code.
# Depends: R (>= 3.0)
# Imports: htmlwidgets (>= 0.3.2), stringr
# License: GPL-3 | file LICENSE
# Suggests: knitr, ggplot2, rmarkdown, testthat, devtools, shiny, htmltools
# RoxygenNote: 6.1.1
# URL: https://rstudio.github.io/profvis/
# Encoding: UTF-8
# NeedsCompilation: yes
# Packaged: 2019-05-14 13:42:46 UTC; barret
# Author: Winston Chang [aut, cre], Javier Luraschi [aut], Timothy Mastny [aut], RStudio [cph], jQuery Foundation [cph] (jQuery library), jQuery contributors [ctb, cph] (jQuery library; authors listed in inst/www/shared/jquery-AUTHORS.txt), Mike Bostock [ctb, cph] (D3 library), D3 contributors [ctb] (D3 library), Ivan Sagalaev [ctb, cph] (highlight.js library)
# Maintainer: Winston Chang <winston@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-05-14 14:20:03 UTC
